console.log("DATE", new Date().toISOString())
console.log("*********************")
console.log("ENV")
console.log("MARIADB_ROOT_PASSWORD", process.env.MARIADB_ROOT_PASSWORD)
console.log("MARIADB_DATABASE", process.env.MARIADB_DATABASE)
console.log("https://medium.com/mariadb/json-tables-with-mariadb-578238cec0c6")
console.log("https://dev.to/frasnym/how-to-create-dockerized-nodejs-with-mysql-database-1o44")
console.log("https://github.com/mysqljs/mysql")
console.log("https://github.com/QTree-app/mysql-json")